language: r
pandoc_version: 1.17
env:
  - TRAVIS_NODE_VERSION="7"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && ./install.sh) && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - echo $PATH
  - npm i -g docsmith
  - npm i -g

script:
  - git clone https://github.com/SAFETAG/SAFETAG
  - echo $PATH
  - DEBUG=* safetag start --source $(pwd)/SAFETAG migrate
  - DEBUG=* safetag link activities ~/.content/build/@safetag/migrate/activities
  - DEBUG=* safetag start --debug toolkit

addons:
  apt:
    packages:
    - pandoc
deploy:
  local_dir: ~/.content/build/@safetag/toolkit
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
